defaults:
  - _self_
  - processing: default
  - dataset: default
  - loss: ??? # Needs to be defined in the experiments/name.yaml
  - lr_scheduler: 1cycle
  - metrics: default
  - model: ??? # Needs to be defined in the experiments/name.yaml
  - optimizer: adamw
  - training: default
  - experiments: ???

# Experiment Parameters
experiment-name: default

# Logging Parameters
logs-path: logs # Path with respect to the root folder
metric-to-track: train/l2
project-name: frame
